# Funding platforms for Nautilus One
# Uncomment and configure as needed

# github: [username]
# patreon: username
# open_collective: nautilus-one
# ko_fi: username
# tidelift: npm/nautilus-one
# custom: ["https://nautilus.app/sponsor"]
