import { supabase } from "@/integrations/supabase/client";

export interface WorkflowAISummary {
  total: number;
  aceitas: number;
  taxa: string;
}

/**
 * Get a summary of AI suggestions for workflows
 * @returns Summary with total suggestions generated, accepted by users, and adoption rate
 */
export async function getWorkflowAISummary(): Promise<WorkflowAISummary> {
  try {
    // Get total suggestions generated by AI
    const { data: allSuggestions, error: totalError } = await supabase
      .from("workflow_ai_suggestions")
      .select("id", { count: "exact" });

    if (totalError) {
      console.error("Error fetching total AI suggestions:", totalError);
      return { total: 0, aceitas: 0, taxa: "0.0" };
    }

    const total = allSuggestions?.length || 0;

    // Get accepted suggestions (those with origem = 'Copilot' are considered accepted)
    const { data: acceptedSuggestions, error: acceptedError } = await supabase
      .from("workflow_ai_suggestions")
      .select("id", { count: "exact" })
      .eq("origem", "Copilot");

    if (acceptedError) {
      console.error("Error fetching accepted AI suggestions:", acceptedError);
      return { total, aceitas: 0, taxa: "0.0" };
    }

    const aceitas = acceptedSuggestions?.length || 0;

    // Calculate adoption rate
    const taxa = total > 0 ? ((aceitas / total) * 100).toFixed(1) : "0.0";

    return {
      total,
      aceitas,
      taxa,
    };
  } catch (error) {
    console.error("Error in getWorkflowAISummary:", error);
    return { total: 0, aceitas: 0, taxa: "0.0" };
  }
}
