/**
 * IMCA DP Technical Audit System - Type Definitions
 * 
 * This file contains TypeScript type definitions for the IMCA (International Marine 
 * Contractors Association) Dynamic Positioning (DP) Technical Audit System.
 * 
 * The system evaluates vessel DP operations against international standards including:
 * - IMCA M103, M117, M190, M166, M109, M220, M140
 * - MSF 182
 * - MTS DP Operations Guidelines
 * - IMO MSC.1/Circ.1580
 */

/**
 * DP vessel classification levels
 */
export type DPClass = 'DP1' | 'DP2' | 'DP3';

/**
 * Risk levels for non-conformities
 */
export type RiskLevel = 'Alto' | 'Médio' | 'Baixo';

/**
 * Priority levels for action items
 */
export type PriorityLevel = 'Crítico' | 'Alto' | 'Médio' | 'Baixo';

/**
 * International standards evaluated in the audit
 */
export interface IMCAStandard {
  code: string;
  name: string;
  description: string;
}

/**
 * DP system module being evaluated
 */
export interface DPModule {
  id: string;
  name: string;
  description: string;
  score: number; // 0-100
  findings: string[];
}

/**
 * Non-conformity identified during audit
 */
export interface NonConformity {
  id: string;
  module: string;
  description: string;
  standard: string;
  riskLevel: RiskLevel;
  recommendation: string;
}

/**
 * Action item for correction plan
 */
export interface ActionItem {
  id: string;
  description: string;
  priority: PriorityLevel;
  deadline: string; // ISO date string
  responsible: string;
  relatedNonConformity?: string;
}

/**
 * Input data for generating an audit
 */
export interface IMCAAuditInput {
  vesselName: string;
  dpClass: DPClass;
  location: string;
  auditObjective: string;
  incidentDetails?: string;
  environmentalConditions?: string;
  systemStatus?: string;
}

/**
 * Complete audit report generated by the system
 */
export interface IMCAAuditReport {
  id: string;
  vesselName: string;
  dpClass: DPClass;
  location: string;
  auditDate: string;
  auditObjective: string;
  overallScore: number; // 0-100
  standards: IMCAStandard[];
  modules: DPModule[];
  nonConformities: NonConformity[];
  actionPlan: ActionItem[];
  summary: string;
  recommendations: string[];
  incidentDetails?: string;
  environmentalConditions?: string;
  systemStatus?: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Audit record stored in database
 */
export interface IMCAAuditRecord {
  id: string;
  user_id: string;
  title: string;
  description?: string;
  status: 'draft' | 'in_progress' | 'completed' | 'approved';
  audit_date?: string;
  score?: number;
  findings: IMCAAuditReport;
  recommendations?: string[];
  metadata?: Record<string, any>;
  created_at: string;
  updated_at: string;
}

/**
 * Standard IMCA standards evaluated
 */
export const IMCA_STANDARDS: IMCAStandard[] = [
  {
    code: 'IMCA M103',
    name: 'Guidelines for DP Operations',
    description: 'Fundamental DP operational guidelines'
  },
  {
    code: 'IMCA M117',
    name: 'DP Operations Guidance',
    description: 'Detailed operational procedures'
  },
  {
    code: 'IMCA M190',
    name: 'Guidance on DP Capability Plots',
    description: 'Requirements for capability plots'
  },
  {
    code: 'IMCA M166',
    name: 'DP FMEA Guidelines',
    description: 'Failure Modes and Effects Analysis requirements'
  },
  {
    code: 'IMCA M109',
    name: 'DP Annual Trials',
    description: 'Annual testing and trials requirements'
  },
  {
    code: 'IMCA M220',
    name: 'DP Incident Reporting',
    description: 'Incident reporting and analysis guidelines'
  },
  {
    code: 'IMCA M140',
    name: 'DP Operations Personnel',
    description: 'Personnel competency and training requirements'
  },
  {
    code: 'MSF 182',
    name: 'Marine Safety Forum Guidelines',
    description: 'Marine safety operational standards'
  },
  {
    code: 'MTS DP',
    name: 'MTS DP Operations Guidelines',
    description: 'Marine Technology Society DP standards'
  },
  {
    code: 'IMO MSC.1/Circ.1580',
    name: 'IMO DP Guidelines',
    description: 'International Maritime Organization DP standards'
  }
];

/**
 * DP system modules evaluated
 */
export const DP_MODULES = [
  {
    id: 'control-systems',
    name: 'Sistemas de Controle',
    description: 'DP control systems and redundancy'
  },
  {
    id: 'propulsion',
    name: 'Sistema de Propulsão',
    description: 'Thrusters and propulsion systems'
  },
  {
    id: 'power',
    name: 'Sistema de Energia',
    description: 'Power generation and distribution'
  },
  {
    id: 'sensors',
    name: 'Sistemas de Sensores',
    description: 'Position reference systems'
  },
  {
    id: 'communications',
    name: 'Comunicações',
    description: 'Communication systems and protocols'
  },
  {
    id: 'personnel',
    name: 'Pessoal',
    description: 'Personnel competency and training'
  },
  {
    id: 'fmea',
    name: 'FMEA',
    description: 'Failure Modes and Effects Analysis'
  },
  {
    id: 'trials',
    name: 'Provas Anuais',
    description: 'Annual trials and testing'
  },
  {
    id: 'documentation',
    name: 'Documentação',
    description: 'Technical documentation and procedures'
  },
  {
    id: 'pms',
    name: 'PMS',
    description: 'Planned Maintenance System'
  },
  {
    id: 'capability',
    name: 'Capability Plots',
    description: 'DP capability plots and analysis'
  },
  {
    id: 'operations',
    name: 'Planejamento Operacional',
    description: 'Operational planning and procedures'
  }
];

/**
 * Helper function to get risk level color for UI
 */
export function getRiskLevelColor(level: RiskLevel): string {
  switch (level) {
    case 'Alto':
      return 'text-red-600 bg-red-50 border-red-200';
    case 'Médio':
      return 'text-yellow-600 bg-yellow-50 border-yellow-200';
    case 'Baixo':
      return 'text-gray-600 bg-gray-50 border-gray-200';
  }
}

/**
 * Helper function to get priority level color for UI
 */
export function getPriorityLevelColor(level: PriorityLevel): string {
  switch (level) {
    case 'Crítico':
      return 'text-red-600 bg-red-50 border-red-200';
    case 'Alto':
      return 'text-orange-600 bg-orange-50 border-orange-200';
    case 'Médio':
      return 'text-yellow-600 bg-yellow-50 border-yellow-200';
    case 'Baixo':
      return 'text-gray-600 bg-gray-50 border-gray-200';
  }
}

/**
 * Helper function to validate DP class
 */
export function isValidDPClass(dpClass: string): dpClass is DPClass {
  return ['DP1', 'DP2', 'DP3'].includes(dpClass);
}

/**
 * Helper function to get deadline based on priority
 */
export function getDeadlineForPriority(priority: PriorityLevel): string {
  const now = new Date();
  switch (priority) {
    case 'Crítico':
      now.setDate(now.getDate() + 7); // 7 days
      break;
    case 'Alto':
      now.setDate(now.getDate() + 30); // 30 days
      break;
    case 'Médio':
      now.setDate(now.getDate() + 90); // 90 days
      break;
    case 'Baixo':
      now.setDate(now.getDate() + 180); // 180 days
      break;
  }
  return now.toISOString().split('T')[0];
}

/**
 * Export audit report as Markdown
 */
export function exportAuditToMarkdown(audit: IMCAAuditReport): string {
  let markdown = `# Auditoria Técnica DP - ${audit.vesselName}\n\n`;
  markdown += `**Classe DP:** ${audit.dpClass}\n`;
  markdown += `**Local:** ${audit.location}\n`;
  markdown += `**Data:** ${new Date(audit.auditDate).toLocaleDateString('pt-BR')}\n`;
  markdown += `**Pontuação Geral:** ${audit.overallScore}/100\n\n`;
  
  markdown += `## Objetivo da Auditoria\n\n${audit.auditObjective}\n\n`;
  
  if (audit.incidentDetails) {
    markdown += `## Detalhes do Incidente\n\n${audit.incidentDetails}\n\n`;
  }
  
  if (audit.environmentalConditions) {
    markdown += `## Condições Ambientais\n\n${audit.environmentalConditions}\n\n`;
  }
  
  markdown += `## Resumo Executivo\n\n${audit.summary}\n\n`;
  
  markdown += `## Normas Avaliadas\n\n`;
  audit.standards.forEach(std => {
    markdown += `- **${std.code}**: ${std.name}\n`;
  });
  markdown += '\n';
  
  markdown += `## Avaliação dos Módulos\n\n`;
  audit.modules.forEach(mod => {
    markdown += `### ${mod.name} - ${mod.score}/100\n\n`;
    if (mod.findings.length > 0) {
      markdown += `**Observações:**\n`;
      mod.findings.forEach(finding => {
        markdown += `- ${finding}\n`;
      });
      markdown += '\n';
    }
  });
  
  markdown += `## Não Conformidades\n\n`;
  audit.nonConformities.forEach((nc, index) => {
    const emoji = nc.riskLevel === 'Alto' ? '🔴' : nc.riskLevel === 'Médio' ? '🟡' : '⚪';
    markdown += `${index + 1}. ${emoji} **${nc.module}** (${nc.riskLevel})\n`;
    markdown += `   - **Norma:** ${nc.standard}\n`;
    markdown += `   - **Descrição:** ${nc.description}\n`;
    markdown += `   - **Recomendação:** ${nc.recommendation}\n\n`;
  });
  
  markdown += `## Plano de Ação\n\n`;
  audit.actionPlan.forEach((action, index) => {
    markdown += `${index + 1}. **${action.description}**\n`;
    markdown += `   - **Prioridade:** ${action.priority}\n`;
    markdown += `   - **Prazo:** ${new Date(action.deadline).toLocaleDateString('pt-BR')}\n`;
    markdown += `   - **Responsável:** ${action.responsible}\n\n`;
  });
  
  markdown += `## Recomendações Gerais\n\n`;
  audit.recommendations.forEach((rec, index) => {
    markdown += `${index + 1}. ${rec}\n`;
  });
  
  return markdown;
}
