import { supabase } from "@/integrations/supabase/client";
import { logger } from "@/lib/logger";
import type { ChecklistItem } from "../types";

interface AIAnalysis {
  overall_score: number;
  issues_found: number;
  critical_issues: number;
  recommendations: string[];
  missing_fields: string[];
  inconsistencies: string[];
}

/**
 * Service for AI-powered checklist suggestions and analysis
 */
export class AIChecklistService {
  /**
   * Generate checklist items using AI
   */
  static async generateChecklistItems(prompt: string): Promise<string[]> {
    try {
      const { data, error } = await supabase.functions.invoke(
        "generate-checklist",
        {
          body: { prompt },
        }
      );

      if (error) throw error;
      if (!data?.items || data.items.length === 0) {
        throw new Error("No items generated by AI");
      }

      return data.items;
    } catch (error) {
      logger.error("Error generating checklist with AI:", error);
      throw error;
    }
  }

  /**
   * Analyze checklist for compliance and issues
   */
  static async analyzeChecklist(
    checklistId: string,
    items: ChecklistItem[]
  ): Promise<AIAnalysis> {
    try {
      // Call AI analysis function
      const { data, error } = await supabase.functions.invoke(
        "analyze-checklist",
        {
          body: {
            checklistId,
            items: items.map(item => ({
              id: item.id,
              title: item.title,
              completed: item.status === "completed",
              required: item.required,
              notes: item.notes
            }))
          }
        }
      );

      if (error) throw error;

      return {
        overall_score: data?.overall_score || 0,
        issues_found: data?.issues_found || 0,
        critical_issues: data?.critical_issues || 0,
        recommendations: data?.recommendations || [],
        missing_fields: data?.missing_fields || [],
        inconsistencies: data?.inconsistencies || []
      };
    } catch (error) {
      logger.error("Error analyzing checklist:", error);
      throw error;
    }
  }

  /**
   * Get AI suggestions for a checklist item
   */
  static async getItemSuggestions(
    itemTitle: string,
    itemDescription?: string,
    context?: Record<string, unknown>
  ): Promise<string[]> {
    try {
      const { data, error } = await supabase.functions.invoke(
        "checklist-item-suggestions",
        {
          body: {
            title: itemTitle,
            description: itemDescription,
            context
          }
        }
      );

      if (error) throw error;
      return data?.suggestions || [];
    } catch (error) {
      logger.error("Error getting item suggestions:", error);
      return [];
    }
  }

  /**
   * Generate checklist summary using AI
   */
  static async summarizeChecklist(
    title: string,
    items: Array<{ title: string; completed: boolean }>,
    comments: string[]
  ): Promise<string> {
    try {
      const { data, error } = await supabase.functions.invoke(
        "summarize-checklist",
        {
          body: { title, items, comments }
        }
      );

      if (error) throw error;
      return data?.summary || "No summary available";
    } catch (error) {
      logger.error("Error summarizing checklist:", error);
      throw error;
    }
  }

  /**
   * Validate checklist item value using AI
   */
  static async validateItemValue(
    itemId: string,
    value: unknown,
    historicalData?: unknown[]
  ): Promise<{
    valid: boolean;
    confidence: number;
    message: string;
    suggestion?: string;
  }> {
    try {
      const { data, error } = await supabase.functions.invoke(
        "validate-checklist-item",
        {
          body: {
            itemId,
            value,
            historicalData
          }
        }
      );

      if (error) throw error;

      return {
        valid: data?.valid || true,
        confidence: data?.confidence || 0,
        message: data?.message || "",
        suggestion: data?.suggestion
      };
    } catch (error) {
      logger.error("Error validating item value:", error);
      return {
        valid: true,
        confidence: 0,
        message: "Validation unavailable"
      };
    }
  }

  /**
   * Get predictive insights for maintenance or issues
   */
  static async getPredictiveInsights(
    vesselId: string,
    checklistType: string,
    historicalChecklists: unknown[]
  ): Promise<string[]> {
    try {
      const { data, error } = await supabase.functions.invoke(
        "predictive-checklist-insights",
        {
          body: {
            vesselId,
            checklistType,
            historicalChecklists
          }
        }
      );

      if (error) throw error;
      return data?.insights || [];
    } catch (error) {
      logger.error("Error getting predictive insights:", error);
      return [];
    }
  }
}
