#!/usr/bin/env tsx
/**
 * Consolidation Script - PATCHES 531-533
 * Removes duplicate admin validation pages and updates routing
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ROOT_DIR = path.join(__dirname, '..');
const PAGES_ADMIN_DIR = path.join(ROOT_DIR, 'src/pages/admin');

interface CleanupTask {
  directory: string;
  reason: string;
  kept?: string;
}

// Duplicate directories to remove
const CLEANUP_TASKS: CleanupTask[] = [
  // PATCH 531: Crew consolidation
  {
    directory: 'crew-consolidado',
    reason: 'Duplicate crew validation - consolidated to crew/',
    kept: 'crew/'
  },
  {
    directory: 'crew-module-consolidation',
    reason: 'Duplicate crew validation - consolidated to crew/',
    kept: 'crew/'
  },
  
  // PATCH 532: Document consolidation
  {
    directory: 'documents-consolidado',
    reason: 'Duplicate document validation - consolidated to document-hub/',
    kept: 'document-hub/'
  },
  {
    directory: 'documents-consolidated',
    reason: 'Duplicate document validation - consolidated to document-hub/',
    kept: 'document-hub/'
  },
  {
    directory: 'documents-consolidation',
    reason: 'Duplicate document validation - consolidated to document-hub/',
    kept: 'document-hub/'
  },
  {
    directory: 'documents-unification',
    reason: 'Duplicate document validation - consolidated to document-hub/',
    kept: 'document-hub/'
  },
  {
    directory: 'document-unification',
    reason: 'Duplicate document validation - consolidated to document-hub/',
    kept: 'document-hub/'
  },
  {
    directory: 'documentation',
    reason: 'Duplicate documentation validation - consolidated to document-hub/',
    kept: 'document-hub/'
  },
  
  // PATCH 533: Mission consolidation
  {
    directory: 'mission-consolidation',
    reason: 'Duplicate mission validation - consolidated to mission-control/',
    kept: 'mission-control/'
  },
  {
    directory: 'mission-control-consolidation',
    reason: 'Duplicate mission validation - consolidated to mission-control/',
    kept: 'mission-control/'
  },
  {
    directory: 'mission-control-realtime',
    reason: 'Duplicate mission validation - consolidated to mission-control/',
    kept: 'mission-control/'
  },
  {
    directory: 'mission-engine-validation',
    reason: 'Duplicate mission validation - consolidated to mission-control/',
    kept: 'mission-control/'
  },
  {
    directory: 'mission-engine-v2',
    reason: 'Duplicate mission validation - consolidated to mission-engine/',
    kept: 'mission-engine/'
  }
];

function removeDirectory(dirPath: string): boolean {
  if (!fs.existsSync(dirPath)) {
    return false;
  }
  
  try {
    // Remove directory recursively
    fs.rmSync(dirPath, { recursive: true, force: true });
    return true;
  } catch (error) {
    console.error(`Error removing ${dirPath}:`, error);
    return false;
  }
}

function generateCleanupReport(): string {
  let report = `# Consolidation Cleanup Report\n\n`;
  report += `**Date**: ${new Date().toISOString()}\n`;
  report += `**Patches**: 531-533\n\n`;
  
  report += `## Summary\n\n`;
  report += `This cleanup removes duplicate validation pages that were created during iterative development.\n`;
  report += `All validation functionality has been consolidated into the primary module directories.\n\n`;
  
  report += `## Directories Removed\n\n`;
  
  for (const task of CLEANUP_TASKS) {
    const dirPath = path.join(PAGES_ADMIN_DIR, task.directory);
    const exists = fs.existsSync(dirPath);
    
    if (exists) {
      report += `- \`${task.directory}/\` ✅ REMOVED\n`;
      report += `  - **Reason**: ${task.reason}\n`;
      if (task.kept) {
        report += `  - **Kept**: \`${task.kept}\`\n`;
      }
    } else {
      report += `- \`${task.directory}/\` ⏭️ ALREADY REMOVED\n`;
    }
  }
  
  report += `\n## Impact\n\n`;
  report += `- Routes in App.tsx will need to be updated to remove references to deleted directories\n`;
  report += `- All validation functionality remains available through consolidated modules\n`;
  report += `- No functionality is lost - only duplicate interfaces removed\n\n`;
  
  report += `## Next Steps\n\n`;
  report += `1. Update App.tsx to remove routes to deleted directories\n`;
  report += `2. Test consolidated validation pages\n`;
  report += `3. Verify no broken links in the application\n\n`;
  
  report += `---\n`;
  report += `*Generated by consolidation script*\n`;
  
  return report;
}

function main() {
  console.log('🧹 Starting consolidation cleanup...\n');
  
  let removed = 0;
  let alreadyGone = 0;
  let failed = 0;
  
  for (const task of CLEANUP_TASKS) {
    const dirPath = path.join(PAGES_ADMIN_DIR, task.directory);
    
    if (!fs.existsSync(dirPath)) {
      console.log(`⏭️  ${task.directory}/ - already removed`);
      alreadyGone++;
      continue;
    }
    
    console.log(`🗑️  Removing ${task.directory}/...`);
    const success = removeDirectory(dirPath);
    
    if (success) {
      console.log(`   ✅ Removed (kept: ${task.kept})`);
      removed++;
    } else {
      console.log(`   ❌ Failed to remove`);
      failed++;
    }
  }
  
  console.log(`\n📊 Summary:`);
  console.log(`   Removed: ${removed}`);
  console.log(`   Already gone: ${alreadyGone}`);
  console.log(`   Failed: ${failed}`);
  
  // Generate report
  const report = generateCleanupReport();
  const reportPath = path.join(ROOT_DIR, 'dev/reports/consolidation_cleanup.md');
  
  const reportsDir = path.dirname(reportPath);
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }
  
  fs.writeFileSync(reportPath, report);
  console.log(`\n📄 Report saved: ${reportPath}`);
  
  console.log(`\n✅ Cleanup complete!`);
  console.log(`\n⚠️  Next: Update App.tsx to remove routes to deleted directories`);
}

main();
