/**
 * PATCH 566 - Demo Steps Configuration
 * Defines the guided tour through key modules
 */

import { DemoStep } from "./types";

export const demoSteps: DemoStep[] = [
  {
    id: "step-1",
    module: "Dashboard",
    title: "Welcome to Nautilus Travel HR Buddy",
    description: "A comprehensive maritime operations platform with AI-powered insights",
    narrative: "Welcome to Nautilus Travel HR Buddy. This is your unified maritime operations platform that combines AI intelligence with practical tools for vessel management, crew coordination, and compliance tracking.",
    route: "/",
    duration: 8000,
  },
  {
    id: "step-2",
    module: "AI Assistant",
    title: "AI-Powered Assistant",
    description: "Your intelligent companion for maritime operations",
    narrative: "Meet your AI Assistant - a sophisticated system that learns from your operations, provides predictive insights, and helps you make data-driven decisions. It analyzes historical data and suggests optimal actions.",
    route: "/ai-assistant",
    duration: 10000,
  },
  {
    id: "step-3",
    module: "Crew Management",
    title: "Smart Crew Management",
    description: "Manage crew assignments, certifications, and wellbeing",
    narrative: "The Crew Management module helps you track crew members, their certifications, assignments, and wellbeing. It includes automated alerts for expiring certifications and optimal crew rotation suggestions.",
    route: "/crew-management",
    duration: 9000,
  },
  {
    id: "step-4",
    module: "MMI Module",
    title: "Marine Maintenance Intelligence",
    description: "Predictive maintenance for vessels",
    narrative: "Marine Maintenance Intelligence uses AI to predict equipment failures before they happen. It analyzes historical maintenance data, equipment age, and usage patterns to schedule optimal maintenance windows.",
    route: "/mmi",
    duration: 10000,
  },
  {
    id: "step-5",
    module: "SGSO Dashboard",
    title: "Safety Management System",
    description: "Comprehensive safety and compliance tracking",
    narrative: "The SGSO Dashboard provides a complete view of your safety management system. Track incidents, conduct audits, monitor compliance metrics, and generate safety reports - all in one place.",
    route: "/sgso",
    duration: 9000,
  },
  {
    id: "step-6",
    module: "DP Intelligence",
    title: "Dynamic Positioning Intelligence",
    description: "Monitor and optimize DP operations",
    narrative: "Dynamic Positioning Intelligence provides real-time monitoring of DP incidents, analyzes trends, and generates actionable insights to improve operational safety and efficiency.",
    route: "/dp-intelligence",
    duration: 9000,
  },
  {
    id: "step-7",
    module: "Document Hub",
    title: "Intelligent Document Management",
    description: "AI-powered document organization and search",
    narrative: "The Document Hub uses AI to automatically categorize documents, extract key information, and enable powerful semantic search. Find what you need instantly, even if you don't know the exact filename.",
    route: "/documents",
    duration: 9000,
  },
  {
    id: "step-8",
    module: "Forecast Module",
    title: "Predictive Analytics",
    description: "Forecast operations and optimize planning",
    narrative: "The Forecast Module analyzes historical patterns and current trends to predict future maintenance needs, crew requirements, and operational costs. Plan ahead with confidence using data-driven forecasts.",
    route: "/forecast",
    duration: 9000,
  },
  {
    id: "step-9",
    module: "Control Hub",
    title: "Centralized Operations Control",
    description: "Monitor and control all systems from one place",
    narrative: "The Control Hub is your command center. Monitor all vessels, track real-time metrics, manage alerts, and coordinate responses across your entire fleet from this unified interface.",
    route: "/control-hub",
    duration: 9000,
  },
  {
    id: "step-10",
    module: "Business Intelligence",
    title: "Advanced Analytics & Reporting",
    description: "Transform data into actionable insights",
    narrative: "Business Intelligence provides powerful analytics tools, customizable dashboards, and automated reporting. Visualize KPIs, track trends, and export data for deeper analysis.",
    route: "/business-intelligence",
    duration: 9000,
  },
  {
    id: "step-11",
    module: "Collaboration",
    title: "Team Collaboration Tools",
    description: "Work together seamlessly across locations",
    narrative: "Collaboration tools enable your team to work together in real-time, share documents, discuss issues, and coordinate responses - whether they're on shore or at sea.",
    route: "/collaboration",
    duration: 8000,
  },
  {
    id: "step-12",
    module: "AI Evolution Dashboard",
    title: "AI Learning & Improvement",
    description: "Watch the AI system learn and evolve",
    narrative: "The AI Evolution Dashboard shows how the system learns from your operations. Track confidence scores, accuracy improvements, and see how the AI adapts to your specific needs over time.",
    route: "/dashboard/ai-evolution",
    duration: 10000,
  },
];
