-- PATCH 597: Smart Scheduler - scheduled_tasks table
-- Migration for creating the scheduled_tasks table and related indexes

-- Create scheduled_tasks table
CREATE TABLE IF NOT EXISTS public.scheduled_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  module TEXT NOT NULL,
  related_entity UUID,
  title TEXT,
  description TEXT NOT NULL,
  priority TEXT NOT NULL CHECK (priority IN ('critical', 'high', 'medium', 'low')),
  due_date TIMESTAMPTZ NOT NULL,
  created_by UUID REFERENCES auth.users(id),
  assigned_to UUID REFERENCES auth.users(id),
  ai_generated BOOLEAN DEFAULT false,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled', 'overdue')),
  source TEXT DEFAULT 'manual' CHECK (source IN ('manual', 'ai_generated', 'inspection', 'watchdog', 'scheduled')),
  tags TEXT[],
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_module ON public.scheduled_tasks(module);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_status ON public.scheduled_tasks(status);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_priority ON public.scheduled_tasks(priority);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_due_date ON public.scheduled_tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_assigned_to ON public.scheduled_tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_ai_generated ON public.scheduled_tasks(ai_generated);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_scheduled_tasks_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER scheduled_tasks_updated_at
  BEFORE UPDATE ON public.scheduled_tasks
  FOR EACH ROW
  EXECUTE FUNCTION update_scheduled_tasks_updated_at();

-- Enable RLS
ALTER TABLE public.scheduled_tasks ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Users can view all scheduled tasks"
  ON public.scheduled_tasks
  FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can create tasks"
  ON public.scheduled_tasks
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update assigned tasks"
  ON public.scheduled_tasks
  FOR UPDATE
  USING (
    auth.uid() = assigned_to OR
    auth.uid() = created_by
  );

CREATE POLICY "Admins can delete tasks"
  ON public.scheduled_tasks
  FOR DELETE
  USING (
    auth.jwt() ->> 'role' = 'admin'
  );

-- Grant permissions
GRANT SELECT, INSERT, UPDATE ON public.scheduled_tasks TO authenticated;
GRANT DELETE ON public.scheduled_tasks TO authenticated;

-- Add comments for documentation
COMMENT ON TABLE public.scheduled_tasks IS 'PATCH 597: AI-powered task scheduling and management system';
COMMENT ON COLUMN public.scheduled_tasks.module IS 'Module that generated or owns this task (e.g., PSC, MLC, LSA)';
COMMENT ON COLUMN public.scheduled_tasks.related_entity IS 'Optional reference to vessel, inspection, or other entity';
COMMENT ON COLUMN public.scheduled_tasks.ai_generated IS 'Whether this task was generated by AI recommendations';
COMMENT ON COLUMN public.scheduled_tasks.metadata IS 'Additional task context including justification and risk scores';
