-- Create mmi_forecasts table for storing AI-generated maintenance forecasts
-- This table stores forecasts generated by the MMI AI system for maintenance predictions

CREATE TABLE IF NOT EXISTS public.mmi_forecasts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  vessel_name TEXT NOT NULL,
  system_name TEXT NOT NULL,
  forecast_text TEXT NOT NULL,
  priority TEXT DEFAULT 'normal' CHECK (priority IN ('baixa', 'normal', 'alta', 'critica')),
  suggested_date DATE,
  component_id UUID REFERENCES public.mmi_components(id) ON DELETE SET NULL,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_mmi_forecasts_vessel ON public.mmi_forecasts (vessel_name);
CREATE INDEX IF NOT EXISTS idx_mmi_forecasts_system ON public.mmi_forecasts (system_name);
CREATE INDEX IF NOT EXISTS idx_mmi_forecasts_component ON public.mmi_forecasts (component_id);
CREATE INDEX IF NOT EXISTS idx_mmi_forecasts_created_at ON public.mmi_forecasts (created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.mmi_forecasts ENABLE ROW LEVEL SECURITY;

-- Create policy to allow authenticated users to read forecasts
CREATE POLICY "Allow authenticated users to read mmi_forecasts"
  ON public.mmi_forecasts
  FOR SELECT
  TO authenticated
  USING (true);

-- Create policy to allow authenticated users to insert forecasts
CREATE POLICY "Allow authenticated users to insert mmi_forecasts"
  ON public.mmi_forecasts
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Create policy to allow service role full access
CREATE POLICY "Allow service role full access to mmi_forecasts"
  ON public.mmi_forecasts
  FOR ALL
  TO service_role
  USING (true);

-- Add comment to table
COMMENT ON TABLE public.mmi_forecasts IS 'Stores AI-generated maintenance forecasts for MMI system';
COMMENT ON COLUMN public.mmi_forecasts.forecast_text IS 'AI-generated forecast description and recommendations';
COMMENT ON COLUMN public.mmi_forecasts.vessel_name IS 'Name of the vessel for this forecast';
COMMENT ON COLUMN public.mmi_forecasts.system_name IS 'System name being forecasted';
