-- Create forecast_history table
-- This table stores AI-generated forecasts for job trends

CREATE TABLE IF NOT EXISTS public.forecast_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source TEXT NOT NULL,
  forecast_summary TEXT NOT NULL,
  created_by TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_forecast_history_created_at ON public.forecast_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_forecast_history_source ON public.forecast_history(source);

-- Add comments for documentation
COMMENT ON TABLE public.forecast_history IS 'Stores historical forecasts generated by AI for job maintenance predictions';
COMMENT ON COLUMN public.forecast_history.id IS 'Unique identifier for each forecast record';
COMMENT ON COLUMN public.forecast_history.source IS 'Source of the forecast (e.g., dev-mock, cron-job, manual)';
COMMENT ON COLUMN public.forecast_history.forecast_summary IS 'AI-generated forecast text with predictions and recommendations';
COMMENT ON COLUMN public.forecast_history.created_by IS 'User or system that generated the forecast';
COMMENT ON COLUMN public.forecast_history.created_at IS 'Timestamp when the forecast was created';

-- Enable Row Level Security
ALTER TABLE public.forecast_history ENABLE ROW LEVEL SECURITY;

-- Create policies for forecast_history
-- Allow authenticated users to read all forecasts
CREATE POLICY "Allow authenticated users to read forecasts"
  ON public.forecast_history
  FOR SELECT
  TO authenticated
  USING (true);

-- Allow service role to insert forecasts
CREATE POLICY "Allow service role to insert forecasts"
  ON public.forecast_history
  FOR INSERT
  TO service_role
  WITH CHECK (true);

-- Allow anon role to insert forecasts (for API routes)
CREATE POLICY "Allow anon to insert forecasts"
  ON public.forecast_history
  FOR INSERT
  TO anon
  WITH CHECK (true);
