-- ===========================
-- INCIDENT ANALYSIS - AI Analysis Results Storage
-- Table for storing AI-powered incident analysis results
-- ===========================

-- Create incident_analysis table
CREATE TABLE IF NOT EXISTS public.incident_analysis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_id TEXT,
  incident_title TEXT NOT NULL,
  analysis_result TEXT NOT NULL,
  analysis_model TEXT DEFAULT 'gpt-4o',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_incident_analysis_incident_id ON public.incident_analysis(incident_id);
CREATE INDEX IF NOT EXISTS idx_incident_analysis_created_at ON public.incident_analysis(created_at DESC);

-- Enable Row Level Security
ALTER TABLE public.incident_analysis ENABLE ROW LEVEL SECURITY;

-- Policy: Allow all authenticated users to read incident_analysis
CREATE POLICY "Allow authenticated users to read incident_analysis"
  ON public.incident_analysis
  FOR SELECT
  TO authenticated
  USING (true);

-- Policy: Allow service role to insert/update incident_analysis (for API)
CREATE POLICY "Allow service role to manage incident_analysis"
  ON public.incident_analysis
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Add table comment
COMMENT ON TABLE public.incident_analysis IS 'Storage for AI-powered incident analysis results generated by the dp-intel-analyze function';

-- Add column comments
COMMENT ON COLUMN public.incident_analysis.id IS 'Unique identifier for the analysis record';
COMMENT ON COLUMN public.incident_analysis.incident_id IS 'Reference to the incident being analyzed (can be from dp_incidents or PEOTRAM)';
COMMENT ON COLUMN public.incident_analysis.incident_title IS 'Title of the incident being analyzed';
COMMENT ON COLUMN public.incident_analysis.analysis_result IS 'Complete AI analysis result in markdown format';
COMMENT ON COLUMN public.incident_analysis.analysis_model IS 'AI model used for analysis (e.g., gpt-4o, gpt-4)';
COMMENT ON COLUMN public.incident_analysis.created_at IS 'Timestamp when the analysis was created';
COMMENT ON COLUMN public.incident_analysis.updated_at IS 'Timestamp when the analysis was last updated';
