-- Create forecast_history table for storing AI-generated maintenance forecasts
-- This table stores historical forecast data generated by the send-real-forecast cron job

CREATE TABLE IF NOT EXISTS public.forecast_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  forecast_summary TEXT NOT NULL,
  source VARCHAR(100) DEFAULT 'manual',
  created_by VARCHAR(255) DEFAULT 'system',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index on created_at for efficient queries
CREATE INDEX IF NOT EXISTS idx_forecast_history_created_at ON public.forecast_history (created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.forecast_history ENABLE ROW LEVEL SECURITY;

-- Create policy to allow authenticated users to read forecast history
CREATE POLICY "Allow authenticated users to read forecast history"
  ON public.forecast_history
  FOR SELECT
  TO authenticated
  USING (true);

-- Create policy to allow service role to insert forecast history
CREATE POLICY "Allow service role to insert forecast history"
  ON public.forecast_history
  FOR INSERT
  TO service_role
  WITH CHECK (true);

-- Create policy to allow authenticated users with proper permissions to insert
CREATE POLICY "Allow authenticated users to insert forecast history"
  ON public.forecast_history
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Add comment to table
COMMENT ON TABLE public.forecast_history IS 'Stores AI-generated maintenance forecasts and predictions';
