-- Create table for AI jobs forecasts history
CREATE TABLE IF NOT EXISTS public.ai_jobs_forecasts (
  id BIGSERIAL PRIMARY KEY,
  forecast_summary TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'AI',
  created_by TEXT NOT NULL DEFAULT 'System',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  trend_data JSONB,
  forecast TEXT NOT NULL
);

-- Add RLS policies
ALTER TABLE public.ai_jobs_forecasts ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read forecasts
CREATE POLICY "Allow authenticated users to read forecasts"
  ON public.ai_jobs_forecasts
  FOR SELECT
  TO authenticated
  USING (true);

-- Allow authenticated users to insert forecasts
CREATE POLICY "Allow authenticated users to insert forecasts"
  ON public.ai_jobs_forecasts
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Add index on created_at for faster queries
CREATE INDEX IF NOT EXISTS idx_ai_jobs_forecasts_created_at 
  ON public.ai_jobs_forecasts(created_at DESC);

-- Add comment to the table
COMMENT ON TABLE public.ai_jobs_forecasts IS 'Stores AI-generated jobs forecasts history';
COMMENT ON COLUMN public.ai_jobs_forecasts.forecast_summary IS 'Brief summary of the forecast';
COMMENT ON COLUMN public.ai_jobs_forecasts.source IS 'Source of the forecast (e.g., AI, Manual)';
COMMENT ON COLUMN public.ai_jobs_forecasts.created_by IS 'User or system that created the forecast';
COMMENT ON COLUMN public.ai_jobs_forecasts.trend_data IS 'Historical trend data used for the forecast';
COMMENT ON COLUMN public.ai_jobs_forecasts.forecast IS 'Full forecast text generated by AI';
