-- Create mmi_forecasts table for storing AI-generated forecasts
-- This table stores maintenance forecasts generated by GPT-4

CREATE TABLE IF NOT EXISTS public.mmi_forecasts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  vessel_id UUID REFERENCES public.vessels(id) ON DELETE SET NULL,
  vessel_name TEXT NOT NULL,
  system_name TEXT NOT NULL,
  hourmeter NUMERIC NOT NULL DEFAULT 0,
  last_maintenance JSONB DEFAULT '[]'::jsonb,
  forecast_text TEXT NOT NULL,
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.mmi_forecasts ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Allow authenticated users to view all forecasts
CREATE POLICY "Users can view mmi_forecasts"
  ON public.mmi_forecasts FOR SELECT
  TO authenticated
  USING (true);

-- Allow authenticated users to create forecasts
CREATE POLICY "Users can create mmi_forecasts"
  ON public.mmi_forecasts FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Allow authenticated users to update forecasts
CREATE POLICY "Users can update mmi_forecasts"
  ON public.mmi_forecasts FOR UPDATE
  TO authenticated
  USING (true);

-- Allow authenticated users to delete forecasts
CREATE POLICY "Users can delete mmi_forecasts"
  ON public.mmi_forecasts FOR DELETE
  TO authenticated
  USING (true);

-- Create indexes for better performance
CREATE INDEX idx_mmi_forecasts_vessel_id ON public.mmi_forecasts(vessel_id);
CREATE INDEX idx_mmi_forecasts_system_name ON public.mmi_forecasts(system_name);
CREATE INDEX idx_mmi_forecasts_created_at ON public.mmi_forecasts(created_at DESC);

-- Create trigger for updated_at
CREATE TRIGGER update_mmi_forecasts_updated_at
  BEFORE UPDATE ON public.mmi_forecasts
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Add comment
COMMENT ON TABLE public.mmi_forecasts IS 'AI-generated maintenance forecasts from GPT-4';
