// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://vnbptmixvwropvanyhdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuYnB0bWl4dndyb3B2YW55aGRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NzczNTEsImV4cCI6MjA3NDE1MzM1MX0.-LivvlGPJwz_Caj5nVk_dhVeheaXPCROmXc4G8UsJcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safe storage adapter that checks for localStorage availability
// This prevents crashes in environments where localStorage is not available (e.g., Cloudflare Workers, SSR)
const safeLocalStorage = (() => {
  try {
    if (typeof window !== "undefined" && window.localStorage) {
      // Test if we can actually use localStorage (may throw in private browsing mode)
      window.localStorage.setItem("__storage_test__", "test");
      window.localStorage.removeItem("__storage_test__");
      return window.localStorage;
    }
  } catch (e) {
    console.warn("localStorage is not available, using in-memory storage fallback");
  }
  
  // Fallback to in-memory storage when localStorage is not available
  const memoryStorage: Record<string, string> = {};
  return {
    getItem: (key: string) => memoryStorage[key] || null,
    setItem: (key: string, value: string) => { memoryStorage[key] = value; },
    removeItem: (key: string) => { delete memoryStorage[key]; },
    clear: () => { Object.keys(memoryStorage).forEach(key => delete memoryStorage[key]); },
    key: (index: number) => Object.keys(memoryStorage)[index] || null,
    length: Object.keys(memoryStorage).length,
  };
})();

// Detecta se é conexão lenta (2G, 3G, satélite, <2Mbps)
const isSlowConnection = (): boolean => {
  if ('connection' in navigator) {
    const conn = (navigator as any).connection;
    return (
      conn?.saveData || 
      conn?.effectiveType === '2g' || 
      conn?.effectiveType === 'slow-2g' || 
      conn?.effectiveType === '3g' ||
      (conn?.downlink && conn.downlink < 2)
    );
  }
  return false;
};

// Custom fetch with retry for maritime satellite connections
// CRITICAL: Otimizado para conexões de 2Mbps e satélite
const customFetch = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
  const MAX_RETRIES = 4;
  const slow = isSlowConnection();
  
  // Timeouts adaptativos para conexões marítimas/satélite
  // Slow: 25s/40s/55s/70s | Normal: 12s/20s/28s/36s
  const getTimeout = (attempt: number) => {
    const base = slow ? 25000 : 12000;
    return base + (attempt * (slow ? 15000 : 8000));
  };
  
  let lastError: Error | null = null;
  
  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    const controller = new AbortController();
    const timeout = getTimeout(attempt);
    const timeoutId = setTimeout(() => controller.abort(), timeout);
    
    // Handle external abort signal (compatible with all browsers)
    const externalSignal = init?.signal;
    let externalAbortHandler: (() => void) | undefined;
    
    if (externalSignal) {
      externalAbortHandler = () => controller.abort();
      externalSignal.addEventListener('abort', externalAbortHandler);
    }
    
    try {
      const response = await fetch(input, {
        ...init,
        signal: controller.signal,
      });
      clearTimeout(timeoutId);
      if (externalSignal && externalAbortHandler) {
        externalSignal.removeEventListener('abort', externalAbortHandler);
      }
      return response;
    } catch (error) {
      clearTimeout(timeoutId);
      if (externalSignal && externalAbortHandler) {
        externalSignal.removeEventListener('abort', externalAbortHandler);
      }
      lastError = error as Error;
      
      // Check if aborted by external signal (user cancelled)
      if (externalSignal?.aborted) {
        throw error;
      }
      
      // Verificar se é erro recuperável (incluindo erros específicos do iOS Safari PWA)
      const isAborted = (error as Error).name === 'AbortError';
      const errorMessage = (error as Error).message || '';
      const isNetworkError = 
        errorMessage.includes('Failed to fetch') ||
        errorMessage.includes('NetworkError') ||
        errorMessage.includes('network') ||
        errorMessage.includes('Network request failed') ||
        errorMessage.includes('fetch') ||
        errorMessage.includes('CORS') ||
        errorMessage.includes('Load failed') ||
        errorMessage.includes('cancelled') ||
        errorMessage.includes('The operation was aborted') ||
        errorMessage.includes('A network error') ||
        errorMessage.includes('The Internet connection appears to be offline');
      
      const isRetryable = isAborted || isNetworkError;
      
      // Se não é recuperável ou é a última tentativa, lançar erro
      if (!isRetryable || attempt === MAX_RETRIES - 1) {
        console.error(`[Supabase] Request failed after ${attempt + 1} attempts:`, errorMessage);
        throw error;
      }
      
      // Backoff exponencial com jitter: 1.5s, 3s, 6s (+ random 0-1s)
      const jitter = Math.random() * 1000;
      const delay = Math.min(1500 * Math.pow(2, attempt) + jitter, 10000);
      console.log(`[Supabase] Retry ${attempt + 1}/${MAX_RETRIES} after ${Math.round(delay)}ms (timeout was ${timeout}ms, slow=${slow})...`);
      await new Promise(resolve => setTimeout(resolve, delay));
    }
  }
  
  throw lastError || new Error('Max retries exceeded');
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeLocalStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce', // Mais seguro para mobile/PWA
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
  global: {
    headers: {
      "x-client-info": "nautilus-travel-hr-buddy",
    },
    fetch: customFetch,
  },
});